version: '3'

services:
  app:
    build: .
    container_name: onsite-app
    volumes:
      - .:/var/www/html
    expose:
      - "80"
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: onsite-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: onsite_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  nginx:
    image: nginx:latest
    container_name: nginx-reverse-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl   # <- tambah ':ro' agar hanya dibaca
    depends_on:
      - app

volumes:
  db_data:
